### PR TITLE
Specify language attribute for DTS data hub's HTML

### PR DESCRIPTION
**Pull request by RR216**
This PR closes the second half of: https://github.com/cityofaustin/atd-data-tech/issues/12898
Here is the deploy preview: https://deploy-preview-409--austin-transportation.netlify.app/
Here are the details:
Add lang="en" to html element of our websites so they meet [W3C Web Content Accessibility Guidelines (WCAG) accessibility standards](https://webaim.org/standards/wcag/checklist#sc3.1.1).

### CODE REVIEW

**Review by amenity — APPROVED** [review]
🇬🇧 ✔️ 🚢

**Review by johnclary — APPROVED** [review]
Screenshot 2023-07-19 at 10 21 51 AM

Looks great to me. Thanks for the TIL! 🚢

**Review by frankhereford — APPROVED** [review]
Thank you!

**Review by mddilley — APPROVED** [review]
Very cool - this was a new learning to me as well. Thanks for getting us up to standard here! 🚀

**Pull request merged**
