### PR TITLE
Migrate to React + NextJS

### PR DESCRIPTION
**Pull request by johnclary**
This PR rebuilds the [Data & Performance Hub ](https://data.mobility.austin.gov/) with React + NextJS. It resolves https://github.com/cityofaustin/atd-data-tech/issues/6482.

For testing and review, the [README](https://github.com/cityofaustin/atd-data-and-performance/tree/6482-jc-hub-v2#readme) has instructions for running locally. A [deploy preview](https://deploy-preview-397--austin-transportation.netlify.app/) is also available.

I'm looking for any and all feedback on the code and documentation. My primary concern is to make this code base as easy to maintain as possible.

### Remaining todos:
- Update [<PageHead/>](https://github.com/cityofaustin/atd-data-and-performance/blob/1a80847fa6897a5f46cdeaa239aca94943b2176e/components/PageHead.js#L6) to use production endpoint.
- Post-merge, cleanup open PRs and branches
- Post-merge, configure a `production` branch and use it for Netlify deploys

### CODE REVIEW

**Comment by patrickm02L** [comment]
Overall it's really nice. I think it could ship as is with one small fix - adding an external link icon next to the title on the Shared Mobility card. 

## Video Break Down

**Good to go**
- Clean layout
- Cards and hover affect work well (:08)
- External link icon by the title are good (:20)
- Responsive states are perfect (2:11)

**Notes**
- Expected external link open in a new page (:32)
- Share Mobility card missing an external link icon (1:06)
- "About" or "Go to Website" CTA would be nice in the top right corner (1:38)
 

https://user-images.githubusercontent.com/5566727/186949822-86ee9856-1ab1-4c93-901b-2d4fd67eb5ac.mp4

**Review by mddilley — APPROVED** [review]
Couldn't sleep and wanted to get a look at this code before it merged. Looks amazing! This is super solid React code - really small and digestible components. I tested out the app locally and in the deploy preview, and I couldn't find any bugs. I really like the mobile view of the map/list/info. ✨ 

You also may have pushed me back on the Bootstrap train 🚂

**Review by patrickm02L — APPROVED** [review]
Thanks for updating the missing external link icon and having the external link cards open up in their own window.

**Comment by johnclary** [comment]
@patrickm02L you bet! I really appreciated the video. Am thinking about the CTA and I might float some ideas via Slack.

**Review by mateoclarke — APPROVED** [review]
Very awesome work! 

serena-williams-tennis

**Review by frankhereford — APPROVED** [review]
I'm woefully late to the party here with my review, but this wonderfully well done. I love the presentation and the styling; very professional. Thanks @johnclary!

**Comment by johnclary** [comment]
re-basing to `gh-pages` branch - i forgot that's where we deploy from :/

**Pull request merged**
