### PR TITLE
updates dark signal symbology to x icon

### LINKED ISSUE #15250: Update symbology/wording of dark traffic signals
A few ideas on wording/symbology on dark traffic signals in the signal monitor here: https://github.com/cityofaustin/atd-data-and-performance/pull/413 

Would like to make it more clear, could require some refactoring.

### PR DESCRIPTION
**Pull request by tillyw**
fixes https://github.com/cityofaustin/atd-data-tech/issues/15250

pretty straightforward update! I agree that the new symbology is more clear. in order for y'all to test it we just need a dark signal record in data tracker, i believe @Charlie-Henry and @ChristinaTremel are working on that! here's a preview of what it should look like.

Screenshot 2024-02-21 at 4 45 02 PM

### CODE REVIEW

**Comment by ChristinaTremel** [comment]
@tillyw and @Charlie-Henry - the MMC put the signal at Cameron and Ferguson to dark for the day so we can test!

**Comment by chiaberry** [comment]
here's the preview link and fake dark signal: https://deploy-preview-416--austin-transportation.netlify.app/signal-monitor?x=-97.677491&y=30.345806&z=14.00

@ChristinaTremel , do they want the x to be contained in a circle, or just be an X?

**Comment by ChristinaTremel** [comment]
@chiaberry I'll show this to the MMC, but I think I prefer the X in the circle!

**Review by Charlie-Henry — APPROVED** [review]
✖️ Looks good! ✅

**Comment by ChristinaTremel** [comment]
Heard back from the MMC and they are happy with it! 🙂

**Review by ChristinaTremel — APPROVED** [review]

**Review by chiaberry — APPROVED** [review]

**Comment by tillyw** [comment]
yay, thanks y'all!! i'll merge it momentarily

**Pull request merged**
